import {ArrowRight,CheckCircle2,MapPin,ShieldCheck,Star,Utensils,Wifi} from "lucide-react"; import LeadForm from "./components/LeadForm";
const properties=[{name:"Divine Residency",address:"F-16, Jhawar Nagar, Kota",near:"Near Allen Sakar & Career Will",tag:"Jhawar Nagar"},{name:"Divine Residency",address:"C-56, Landmark City, Kunadi, Kota",near:"Near Allen Samyak",tag:"Landmark City"},{name:"Divine Home",address:"D-8, Landmark City, Kunadi, Kota",near:"Near Allen Sangyan",tag:"Landmark City"},{name:"Divine Home",address:"G-62, Coral Park, Kota",near:"Near Allen Supath",tag:"Coral Park"}];
export default function Home(){return <main>
<section className="hero text-white"><nav className="container flex items-center justify-between py-6"><div className="text-2xl font-semibold">Divine<span className="gold">Stays</span></div><a href="#properties" className="rounded-full border border-white/20 px-5 py-2.5 text-sm">Explore stays</a></nav>
<div className="container grid min-h-[660px] items-center gap-12 py-20 lg:grid-cols-[1.1fr_.9fr]"><div><p className="mb-5 text-sm font-semibold uppercase tracking-[.25em] text-[#d9b36b]">Kota · Student Living</p><h1 className="serif max-w-3xl text-5xl leading-[1.03] sm:text-7xl">Your new home in <span className="text-[#d9b36b]">Kota.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/70">Comfortable stays in the places students actually want to live — close to coaching, essentials and everyday life.</p><div className="mt-9 flex gap-3"><a href="#lead" className="inline-flex items-center gap-2 rounded-full bg-[#c9953d] px-6 py-3.5 font-semibold text-black">Find my stay <ArrowRight size={18}/></a><a href="#properties" className="inline-flex rounded-full border border-white/20 px-6 py-3.5 font-semibold">View properties</a></div><div className="mt-12 flex flex-wrap gap-7 text-sm text-white/60"><span><ShieldCheck size={17} className="mr-2 inline"/>Safe & secure</span><span><Wifi size={17} className="mr-2 inline"/>Wi-Fi ready</span><span><Utensils size={17} className="mr-2 inline"/>Food options</span></div></div><LeadForm/></div></section>
<section id="properties" className="container py-24"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] gold">Our locations</p><h2 className="serif mt-3 text-4xl sm:text-5xl">Four stays. One standard.</h2></div><p className="max-w-md text-sm leading-6 text-[#706b61]">Real DivineStays locations across Kota, organized around the coaching hubs our residents care about.</p></div>
<div className="mt-12 grid gap-6 md:grid-cols-2">{properties.map((p,i)=><article key={i} className="card overflow-hidden rounded-[28px] border border-[#e7e0d4] bg-white"><div className="relative h-56 bg-gradient-to-br from-[#353029] via-[#62513a] to-[#171614] p-7 text-white"><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs">{p.tag}</span><div className="absolute bottom-7 left-7"><p className="text-sm text-[#e0c28b]"><MapPin size={14} className="mr-1 inline"/>{p.address}</p><h3 className="serif mt-2 text-3xl">{p.name}</h3></div></div><div className="p-7"><p className="font-semibold">{p.near}</p><p className="mt-3 text-sm leading-6 text-[#706b61]">Student-first accommodation with a focus on convenience, comfort and a reliable living experience.</p><div className="mt-5 flex items-center justify-between"><span className="flex items-center gap-1 text-sm"><Star size={15} fill="currentColor"/> 4.8</span><a href="#lead" className="inline-flex items-center gap-2 text-sm font-bold">Get best deal <ArrowRight size={16}/></a></div></div></article>)}</div></section>
<section className="bg-[#1b1a18] py-24 text-white"><div className="container grid gap-12 md:grid-cols-3">{[['01','Tell us what you need','Budget, location, room preference and move-in date.'],['02','We match your stay','Our team helps you choose the right DivineStays location.'],['03','Visit & move in','Get your quote, schedule a visit and settle in.']].map(x=><div key={x[0]}><p className="gold text-4xl font-bold">{x[0]}</p><h3 className="mt-4 text-xl font-semibold">{x[1]}</h3><p className="mt-2 text-sm leading-6 text-white/55">{x[2]}</p></div>)}</div></section>
<section id="lead" className="container py-24"><div className="rounded-[32px] bg-white p-8 sm:p-12"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-sm font-bold uppercase tracking-[.2em] gold">No endless searching</p><h2 className="serif mt-3 text-4xl">Tell us what you’re looking for.</h2><p className="mt-5 text-sm leading-7 text-[#706b61]">Share your requirements and our team will help you find the right DivineStays property.</p><div className="mt-7 space-y-3 text-sm"><p><CheckCircle2 className="mr-2 inline gold" size={18}/>Quick response</p><p><CheckCircle2 className="mr-2 inline gold" size={18}/>Multiple room options</p><p><CheckCircle2 className="mr-2 inline gold" size={18}/>Direct assistance</p></div></div><LeadForm/></div></div></section>
<footer className="border-t border-[#e7e0d4] py-8"><div className="container text-sm text-[#706b61]">© 2026 DivineStays · Kota, Rajasthan</div></footer>
</main>}